aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: cd website && yarn install && yarn build
      - run:
          name: Deploy to Surge.sh
          command: |
            export PATH="$PATH:$(yarn global bin)"
            yarn global add surge
            surge --project website/build/today-i-learned/ --domain teach.uddin.io

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master
