aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout
      - run:
          name: Deploy to Surge.sh
          command: |
            echo "Installing dependencies and building..."
            cd website && yarn install && yarn build
            echo "Deploying to Surge.sh..."
            surge --project build/today-i-learned/ --domain teach.rakinu.com

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master
